[package]
name = "learn-graphql"
version = "1.0.0"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
authors = [
    "dapod93 <davidliois50@gmail.com>",
]

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
dotenv = "0.15.0"
juniper = "0.16.1"
log = "0.4.27"
